version: '3.9'

services:
  web:
    build:
      context: .
    volumes:
      - ./byd90/app:/code/app
      - ./.env:/code/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: byd90_db
    ports:
      - "5432:5432"
    volumes:
      - byd90_pgdata:/var/lib/postgresql/data

volumes:
  byd90_pgdata:
