version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: byd90_db
    ports:
      - "5432:5432"
    volumes:
      - byd90_pgdata:/var/lib/postgresql/data

volumes:
  byd90_pgdata:
